// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	State                uint32               `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_212b5478ce1bdd37, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetUser struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUser) Reset()         { *m = GetUser{} }
func (m *GetUser) String() string { return proto.CompactTextString(m) }
func (*GetUser) ProtoMessage()    {}
func (*GetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_212b5478ce1bdd37, []int{1}
}
func (m *GetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUser.Unmarshal(m, b)
}
func (m *GetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUser.Marshal(b, m, deterministic)
}
func (dst *GetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUser.Merge(dst, src)
}
func (m *GetUser) XXX_Size() int {
	return xxx_messageInfo_GetUser.Size(m)
}
func (m *GetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUser.DiscardUnknown(m)
}

var xxx_messageInfo_GetUser proto.InternalMessageInfo

func (m *GetUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUser struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUser) Reset()         { *m = ListUser{} }
func (m *ListUser) String() string { return proto.CompactTextString(m) }
func (*ListUser) ProtoMessage()    {}
func (*ListUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_212b5478ce1bdd37, []int{2}
}
func (m *ListUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUser.Unmarshal(m, b)
}
func (m *ListUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUser.Marshal(b, m, deterministic)
}
func (dst *ListUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUser.Merge(dst, src)
}
func (m *ListUser) XXX_Size() int {
	return xxx_messageInfo_ListUser.Size(m)
}
func (m *ListUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUser.DiscardUnknown(m)
}

var xxx_messageInfo_ListUser proto.InternalMessageInfo

func (m *ListUser) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*GetUser)(nil), "api.GetUser")
	proto.RegisterType((*ListUser)(nil), "api.ListUser")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_212b5478ce1bdd37) }

var fileDescriptor_user_212b5478ce1bdd37 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x95, 0x97, 0xf6, 0x69, 0x2e, 0xea, 0x33, 0x58, 0x0c, 0x56, 0x24, 0x44, 0x94, 0x29,
	0x2c, 0xae, 0x14, 0x26, 0xc6, 0xb2, 0xb0, 0x30, 0x05, 0x58, 0x58, 0x90, 0x53, 0x1f, 0x95, 0x25,
	0x82, 0x2d, 0xfb, 0x02, 0xdf, 0x95, 0x4f, 0x83, 0xec, 0x34, 0x0c, 0x08, 0x89, 0xf1, 0xff, 0x76,
	0xfa, 0x1d, 0xc0, 0xe4, 0xd1, 0x09, 0xeb, 0x0c, 0x19, 0x96, 0x49, 0xab, 0xab, 0x8b, 0xa3, 0x31,
	0xc7, 0x57, 0xdc, 0x45, 0x6b, 0x98, 0x5e, 0x76, 0xa4, 0x47, 0xf4, 0x24, 0x47, 0x3b, 0xb7, 0x9a,
	0xcf, 0x04, 0xf2, 0x47, 0x8f, 0x8e, 0xfd, 0x87, 0x54, 0x2b, 0x9e, 0xd4, 0x49, 0x5b, 0xf4, 0xa9,
	0x56, 0xac, 0x82, 0x4d, 0x38, 0xf6, 0x26, 0x47, 0xe4, 0x69, 0x74, 0xbf, 0x75, 0xc8, 0xac, 0xf4,
	0xfe, 0xc3, 0x38, 0xc5, 0xb3, 0x39, 0x5b, 0x34, 0x3b, 0x83, 0x95, 0x27, 0x49, 0xc8, 0xf3, 0x3a,
	0x69, 0xb7, 0xfd, 0x2c, 0xd8, 0x35, 0xc0, 0xc1, 0xa1, 0x24, 0x54, 0xcf, 0x92, 0xf8, 0xaa, 0x4e,
	0xda, 0xb2, 0xab, 0xc4, 0x0c, 0x27, 0x16, 0x38, 0xf1, 0xb0, 0xc0, 0xf5, 0xc5, 0xa9, 0xbd, 0xa7,
	0x30, 0x9d, 0xac, 0x5a, 0xa6, 0xeb, 0xbf, 0xa7, 0xa7, 0xf6, 0x9e, 0x9a, 0x16, 0xfe, 0xdd, 0x22,
	0xc5, 0xf7, 0xce, 0x21, 0x0f, 0xf8, 0xf1, 0xc1, 0xb2, 0x2b, 0x84, 0xb4, 0x5a, 0x84, 0xa0, 0x8f,
	0x76, 0x73, 0x09, 0x9b, 0x3b, 0xed, 0x7f, 0x56, 0xb3, 0x5f, 0xaa, 0xdd, 0x16, 0xca, 0xa0, 0xee,
	0xd1, 0xbd, 0xeb, 0x03, 0xde, 0xe4, 0x4f, 0xa9, 0x1d, 0x86, 0x75, 0x04, 0xb9, 0xfa, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x3c, 0x73, 0xc6, 0xcf, 0x81, 0x01, 0x00, 0x00,
}
